name: Build Windows Release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Windows package
        run: npm run package

      - name: Create Windows installer
        run: npx electron-forge make --platform win32

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-assets
          path: |
            out/make/squirrel.windows/x64/*.exe
            out/make/zip/win32/x64/*.zip
            out/file-search-win32-x64/

      - name: Publish to GitHub Releases
        run: npx electron-forge publish --platform win32
        env:
          # Use your Personal Access Token instead of GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}